name: htv_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0' # Ensure compatibility with null safety

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^8.3.12
  provider: ^6.0.3
  flutter_tts: ^3.3.7
  image_picker: ^0.8.4+4
  http: ^0.13.4
  path_provider: ^2.0.11
  speech_to_text: ^6.5.1

  #googleapis: ^11.0.0 # Ensure this version or a compatible one
 # googleapis_auth: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true