name: HearTheVisionG
description: "HearTheVision with Gemini."
publish_to: 'none'

version: 1.0.2

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.4
  path_provider: ^2.0.11
  google_ml_kit: ^0.10.0
  image: ^3.0.1
  http: ^1.2.2
  flutter_tts: ^3.2.2
  speech_to_text: ^6.6.1
  tflite_flutter: ^0.10.1
  logger: ^1.0.0
  camera: ^0.9.4+5
  url_launcher: ^6.0.9
  permission_handler: ^10.2.0
  google_generative_ai: ^0.4.3
  web_socket_channel: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/splash/splash.png
    - assets/mobilenet_ssd.tflite
    - assets/labels.txt
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #